# Generated by Django 2.1.7 on 2019-02-23 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20190223_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(default='')),
                ('version', models.CharField(max_length=100)),
                ('release_date', models.DateField(default=None)),
                ('delivery_date', models.DateField(default=None)),
                ('release_log', models.TextField(default=None)),
                ('comment', models.TextField(default='')),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_releases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_releases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='')),
                ('details', models.TextField(default='')),
                ('code', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('description', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Analysing'), (3, 'Analysis Complete'), (4, 'Developing'), (5, 'Development Complete'), (6, 'Delivered')], default=1)),
                ('comment', models.TextField(default='')),
                ('analysed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysed_user_stories', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_id',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Started'), (2, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private'), (3, 'In House')], default=1),
        ),
        migrations.AddField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='release',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Release'),
        ),
        migrations.AddField(
            model_name='release',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
