# Generated by Django 2.1.7 on 2019-02-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190223_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Completed')], default=1),
        ),
    ]
