# Generated by Django 2.1.7 on 2019-02-24 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_issue_label_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('day_wise_label', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'On Going'), (3, 'Completed')], default=1)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('category', models.IntegerField(choices=[(1, 'Analysis'), (2, 'Development'), (3, 'Testing'), (4, 'Implementation')], default=1)),
                ('estimation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('assign_date', models.DateField(default=None)),
                ('approved_date', models.DateField(default=None)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Partially Done'), (4, 'Done'), (5, 'Delivered'), (6, 'Not Done'), (7, 'Rejected')], default=1)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_tasks', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Issue')),
                ('parent_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
                ('priority', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Priority')),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project')),
                ('responsible', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sprint')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserStory')),
            ],
        ),
    ]
