# Generated by Django 2.1.7 on 2019-02-24 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_deliverable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=None)),
                ('estimated_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('actual_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('comment', models.TextField(default='')),
                ('deliverable', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Deliverable')),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project')),
                ('release', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Release')),
                ('sprint', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sprint')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_story', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserStory')),
            ],
        ),
    ]
