# Generated by Django 2.1.7 on 2019-02-24 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_dailyscrum'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=None)),
                ('description', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Partially Done'), (4, 'Done'), (5, 'Delivered'), (6, 'Not Done'), (7, 'Rejected')], default=1)),
                ('assigned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_over_times', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_over_times', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project')),
            ],
        ),
    ]
