# Generated by Django 2.1.7 on 2019-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190316_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_log',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
