# Generated by Django 2.1.7 on 2019-03-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190316_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='analysed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysed_user_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Analysing'), (3, 'Analysis Complete'), (4, 'Developing'), (5, 'Development Complete'), (6, 'Delivered')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='summary',
            field=models.TextField(default='', verbose_name='Title'),
        ),
    ]
