# Generated by Django 2.1.7 on 2019-03-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190318_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='approved_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issues', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='raised_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_issues', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='analysed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysed_user_stories', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_stories', to='core.Employee'),
        ),
    ]
