# Generated by Django 2.1.7 on 2019-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190318_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
