# Generated by Django 2.1.7 on 2019-03-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190318_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.IntegerField(choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Miss')], default=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Vendor')], default=1),
        ),
    ]
