# Generated by Django 2.1.7 on 2019-04-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190326_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'permissions': (('dev_dashboard', 'Can See Dev Dashboard'),)},
        ),
    ]
