# Generated by Django 2.1.7 on 2019-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20190507_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
