# Generated by Django 2.1.7 on 2019-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20190507_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
