# Generated by Django 2.1.7 on 2019-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20190508_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='party',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.IntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Miss')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
