# Generated by Django 2.1.7 on 2019-05-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190508_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='password',
        ),
        migrations.RemoveField(
            model_name='party',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
