# Generated by Django 2.1.7 on 2019-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Repository URL'),
        ),
    ]
