# Generated by Django 2.2.1 on 2019-05-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20190509_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('update_sprint_status', 'Can Update Status of Sprint'), ('status_report', 'Can See Sprint Status Report'))},
        ),
    ]
