# Generated by Django 2.2.1 on 2019-05-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20190509_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscrum',
            name='estimated_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Point'),
        ),
    ]
