# Generated by Django 2.2.1 on 2019-05-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('update_sprint_status', 'Can Update Status of Sprint'), ('sprint_status_report', 'Can See Sprint Status Report'), ('sprint_status_report_download', 'Can Download Sprint Status Report'))},
        ),
    ]
