# Generated by Django 2.2.1 on 2019-05-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190509_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('update_project_status', 'Can Update Status of Project'), ('view_commit_logs', 'Can View Commit Logs of Project'), ('project_status_report', 'Can See Project Status Report'), ('project_status_report_download', 'Can Download Project Status Report'))},
        ),
    ]
