# Generated by Django 2.2.1 on 2019-05-16 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190509_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project'),
        ),
    ]
