# Generated by Django 2.2.1 on 2019-05-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deliverable_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='user_story',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserStory'),
        ),
    ]
