# Generated by Django 2.1.7 on 2019-02-24 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20190224_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardPortlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1)),
                ('height', models.DecimalField(decimal_places=2, default=50, max_digits=15)),
                ('width', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Portlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('html_template', models.CharField(max_length=100)),
                ('data_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_text', models.TextField(default='')),
                ('activity_data', models.TextField(default='')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dashboardportlet',
            name='portlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Portlet'),
        ),
    ]
