# Generated by Django 2.2.1 on 2019-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.IntegerField(choices=[(1, 'ProjectOwner'), (2, 'TeamLead'), (3, 'Developer')], default=3),
        ),
    ]
