# Generated by Django 2.2.1 on 2019-05-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190520_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectCommitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('author_name', models.CharField(max_length=128)),
                ('author_email', models.CharField(max_length=128)),
                ('author_url', models.URLField(max_length=128)),
                ('author_html_url', models.URLField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
    ]
