# Generated by Django 2.2.1 on 2019-06-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deliverable_actual_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('update_project_status', 'Can Update Status of Project'), ('view_commit_logs', 'Can View Commit Logs of Project'), ('project_status_report', 'Can See Project Status Report'), ('project_status_report_download', 'Can Download Project Status Report'), ('project_members', 'Can See Members of a Project'), ('assign_deliverable', 'Can Assign Deliverables'))},
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='actual_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Actual Point'),
        ),
    ]
