# Generated by Django 2.1.7 on 2019-03-16 06:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='sub_type',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('party_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Party')),
                ('sub_type', models.IntegerField(choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Vendor')])),
            ],
            bases=('core.party',),
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
        migrations.RemoveField(
            model_name='department',
            name='division',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sprint',
        ),
        migrations.AlterField(
            model_name='project',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='issue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Issue'),
        ),
    ]
