# Generated by Django 2.2.2 on 2019-06-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190602_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardportlet',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardportlet',
            name='portlet',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardPortlet',
        ),
        migrations.DeleteModel(
            name='Portlet',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
