# Generated by Django 2.2.2 on 2019-06-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190605_0531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyScrum',
        ),
    ]
