# Generated by Django 2.2.2 on 2019-06-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historicaldeliverable_historicalissue_historicalovertime_historicalproject_historicalprojectcommitlo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('update_project_status', 'Can Update Status of Project'), ('view_commit_logs', 'Can View Commit Logs of Project'), ('project_status_report', 'Can See Project Status Report'), ('project_status_report_download', 'Can Download Project Status Report'), ('project_members', 'Can See Members of a Project'), ('assign_deliverable', 'Can Assign Deliverables'), ('project_history', 'Can See Project History'))},
        ),
    ]
