# Generated by Django 2.2.2 on 2019-06-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190622_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'permissions': (('update_deliverable_status', 'Can Update Status of Deliverable'), ('deliverable_history', 'Can See Deliverable History'))},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': (('update_issue_status', 'Can Update Status of Issue'), ('issue_history', 'Can See Issue History'))},
        ),
        migrations.AlterModelOptions(
            name='overtime',
            options={'permissions': (('over_time_history', 'Can See Over Time History'),)},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'permissions': (('project_member_history', 'Can See Project Member History'),)},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'permissions': (('release_history', 'Can See Release History'),)},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('update_sprint_status', 'Can Update Status of Sprint'), ('sprint_status_report', 'Can See Sprint Status Report'), ('sprint_status_report_download', 'Can Download Sprint Status Report'), ('sprint_history', 'Can See Sprint History'))},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('update_task_status', 'Can Update Status of Task'), ('task_history', 'Can See Task History'))},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'permissions': (('update_user_story_status', 'Can Update Status of User Story'), ('user_story_history', 'Can See User Story History'))},
        ),
    ]
