# Generated by Django 2.1.7 on 2019-03-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190318_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='department_id',
            new_name='department',
        ),
    ]
