# Generated by Django 2.1.7 on 2019-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190318_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Vendor')], default=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Vendor')], default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='sub_type',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Organization')], default=2),
        ),
    ]
