# Generated by Django 2.1.7 on 2019-03-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190319_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyscrum',
            name='user',
        ),
        migrations.AddField(
            model_name='dailyscrum',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='dailyscrum',
            name='actual_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dailyscrum',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='dailyscrum',
            name='entry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailyscrum',
            name='estimated_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
