# Generated by Django 2.1.7 on 2019-03-20 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_party_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to=settings.AUTH_USER_MODEL),
        ),
    ]
