# Generated by Django 2.1.7 on 2019-03-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190325_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='project',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='release',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='user_story',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='release',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Release'),
        ),
    ]
