# Generated by Django 2.1.7 on 2019-03-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190326_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('update_task_status', 'Can Update Status of Task'),)},
        ),
    ]
