# Generated by Django 2.1.7 on 2019-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20190326_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': (('update_issue_status', 'Can Update Status of Issue'),)},
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Partially Done'), (4, 'Done'), (5, 'Delivered'), (6, 'Not Done'), (7, 'Rejected')], default=1),
        ),
    ]
