# Generated by Django 2.1.7 on 2019-05-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190429_0257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('update_project_status', 'Can Update Status of Project'),)},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('update_sprint_status', 'Can Update Status of Sprint'),)},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'permissions': (('update_user_story_status', 'Can Update Status of User Story'),)},
        ),
    ]
