# Generated by Django 2.1.7 on 2019-05-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20190507_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_tasks', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_tasks', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Analysis'), (2, 'Development'), (3, 'Testing'), (4, 'Implementation')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='release',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Release'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_tasks', to='core.Employee'),
        ),
    ]
