# Generated by Django 2.2.1 on 2019-05-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_project_repo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repo_url',
        ),
        migrations.AddField(
            model_name='project',
            name='git_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Github Password'),
        ),
        migrations.AddField(
            model_name='project',
            name='git_repo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Github Repo'),
        ),
        migrations.AddField(
            model_name='project',
            name='git_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Github Username'),
        ),
    ]
