# Generated by Django 2.2.1 on 2019-05-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20190509_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('update_project_status', 'Can Update Status of Project'), ('view_commit_logs', 'Can View Commit Logs of Project'))},
        ),
    ]
