# Generated by Django 2.2.1 on 2019-05-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20190509_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='estimated_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Done'), (4, 'Delivered'), (5, 'Rejected')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Done'), (4, 'Delivered'), (5, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Done'), (4, 'Delivered'), (5, 'Rejected')], default=1),
        ),
    ]
