# Generated by Django 2.2.1 on 2019-05-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20190509_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('update_sprint_status', 'Can Update Status of Sprint'), ('status_report', 'Can See Sprint Status Report'), ('status_report_download', 'Can Download Sprint Status Report'))},
        ),
    ]
