# Generated by Django 2.2.2 on 2019-06-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_historicaluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('client_history', 'Can See Client History'),)},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('employee_history', 'Can See Employee History'),)},
        ),
    ]
